/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlarmClock;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Asif
 */
public class Alarm extends javax.swing.JFrame {

    /**
     * Creates new form Alarm
     */
    Timer updateTimer;
    int DELAY = 100;
    
   
    
    
    
    public Alarm() {
        initComponents();
        
        updateTimer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date currentTime = new Date();
               String formatTimStr = "hh:mm:ss";
               DateFormat formatTime = new SimpleDateFormat(formatTimStr);
               String formatedTimeString = formatTime.format(currentTime);
                               
               clock_time.setText(formatedTimeString);
              
               
            }
        });
        updateTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock_time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jHH = new javax.swing.JTextField();
        jMM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clock_time.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        clock_time.setText("00:00:00");

        jButton1.setText("Set Alarm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jHH.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jHH.setText("0");
        jHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHHActionPerformed(evt);
            }
        });

        jMM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jMM.setText("0");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(clock_time)
                            .addGap(234, 234, 234))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(331, 331, 331)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clock_time, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHH))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int hour24 = LocalDateTime.now().getHour();
        int minute = LocalDateTime.now().getMinute();
        int hour = hour24;
        if (hour24 > 12) {
            hour = (hour24-12);
        }
 
        // this is where all the problem
//        String mm = jMM.getText();
        int mmm = Integer.getInteger(jMM.getText());
        int mmmm= Integer.parseInt(jMM.getText());
        int a = 0;
        jHH.setText(""+mmm);
        jLabel1.setText(" "+ a);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHHActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jHHActionPerformed

    /**
     * @param args the command line arguments
     */
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jHH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jMM;
    // End of variables declaration//GEN-END:variables
}
